### ISSUE TITLE
Can updates/obsoletes contain whitespace?

### ISSUE THREAD

**Issue by martinthomson** [interim-rfc-series-project-manager/draft-irse-xml2rfcv3-implemented#4]
The `updates` and `obsoletes` attributes on the `<rfc>` element are defined as follows:

>  A comma-separated list of RFC numbers or Internet-Draft names.

However, in practice, this has been implemented to allow whitespace.  The specification should say that.

A further wrinkle though: we need to be very careful about what "whitespace" means.  RFC 8996 includes several Unicode zero-width space characters (U+200b) in this attribute.  That is technically whitespace, but it is not whitespace that python recognizes.  Therefore, it is not stripped out by xml2rfc.  This is currently causing problems in HTML generation.

**Comment by martinthomson** [comment]
Oh, I realize that maybe "whitespace" implicitly follows the [XML definition of white space](https://www.w3.org/TR/2008/REC-xml-20081126/#sec-white-space), which only includes U+20, U+09, U+0a, and U+0d.  That would line up with what python does.

**Comment by jrlevine** [comment]
updated draft
