### ISSUE TITLE
postalLine and country

### ISSUE THREAD

**Issue by martinthomson** [interim-rfc-series-project-manager/draft-irse-xml2rfcv3-implemented#5]
[Section 3.37](https://www.ietf.org/archive/id/draft-irse-draft-irse-xml2rfcv3-implemented-01.html#section-3.37-2) says:

> The sub-elements other than <[postalLine](https://www.ietf.org/archive/id/draft-irse-draft-irse-xml2rfcv3-implemented-01.html#element.postalLine)> and <[country](https://www.ietf.org/archive/id/draft-irse-draft-irse-xml2rfcv3-implemented-01.html#element.country)> have been deprecated and will likely be removed in a future version.

This doesn't allow someone to specify a country AND additional postalLine elements.  It seems like that would be a useful construction: a country to satisfy basic data collection requirements, but then free form information for any remainder.

**Comment by jrlevine** [comment]
Yes it does, the intent is that it's a sequence of PostalLine and an optional Country.
The current grammar doesn't allow the Country after PostalLine so I'll have to move that bit to a section on proposed but not implemented changes.
